server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;

    location /dnd-card-maker {
        index index.html;
        try_files $uri $uri/ /dnd-card-maker/index.html;
    }
}